language: node_js
node_js:
  - stable
branches:
  only:
  - master
install:
  - git config --global user.email "cody.sehl+travis@gmail.com"
  - git config --global user.name "Travis"
  - npm install
script:
  - npm run build production
after_success:
  - ./travis/commit.sh
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git push -f https://github.com/lalunamel/blog.git gh-pages
env:
  global:
    secure: N6GPqP7YdPSoeWNSNq5Z7pqiYdH6kF8FMbhNIzpLikwBQJU26wxKNRSlg4twR+BYZmGQssjyC0aoo/vCQ3vbc28heXOad1eCFabyAGNS7TxFeYSEuMKsyU4RHs0q1ta19FuL0znodTigZKM66yaRbq3P94ajfKfGoutjJgxJ9vE=
